import assert from "node:assert/strict";
import { mkdir, mkdtemp, readdir, readFile, rename, rm, symlink, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { pathToFileURL } from "node:url";
import { DefaultResourceLoader, type ExtensionContext, SettingsManager } from "@earendil-works/pi-coding-agent";
import { createRpcHarness } from "@narumitw/pi-tui-kit/testing";
import { test } from "vitest";

const packageRoot = resolve("packages/pi-ticker");
const builderUrl = pathToFileURL(join(packageRoot, "scripts/build-runtime.mjs")).href;
const forbiddenEagerInputs = ["src/menu.ts", "src/tui-menu.ts"] as const;
const generatedBanner = [
  "// @generated by scripts/build-runtime.mjs; do not edit.",
  "// @ts-nocheck -- generated JavaScript uses a .ts extension for Pi's Jiti loader.",
].join("\n");

type BuildMetadata = {
  outputs?: Record<
    string,
    {
      entryPoint?: string;
      imports?: Array<{ external?: boolean; kind?: string; path: string }>;
      inputs?: Record<string, unknown>;
    }
  >;
};

type RuntimeBuilder = {
  buildRuntime(options?: {
    outputDirectory?: string;
    validateOutput?: (outputDirectory: string) => Promise<void>;
  }): Promise<BuildMetadata>;
  validateEagerGraph(metadata: BuildMetadata): {
    eagerInputs: Set<string>;
    eagerOutputs: Set<string>;
  };
  validateGeneratedFiles(outputDirectory: string): Promise<void>;
  publishRuntime(
    stagingDirectory: string,
    outputDirectory: string,
    operations?: { renamePath?: typeof rename },
  ): Promise<void>;
};

async function loadBuilder(): Promise<RuntimeBuilder> {
  return (await import(`${builderUrl}?test=${crypto.randomUUID()}`)) as RuntimeBuilder;
}

function validMetadata(): BuildMetadata {
  const menuOutput = "dist/chunks/menu.js";
  const tuiOutput = "dist/chunks/tui-menu.js";
  return {
    outputs: {
      "dist/index.ts": {
        entryPoint: "src/index.ts",
        imports: [
          {
            path: "@earendil-works/pi-coding-agent",
            kind: "import-statement",
            external: true,
          },
          {
            path: "@narumitw/pi-tui-kit/terminal-text",
            kind: "import-statement",
            external: true,
          },
          { path: menuOutput, kind: "dynamic-import" },
        ],
        inputs: { "src/index.ts": {}, "src/ticker.ts": {} },
      },
      [menuOutput]: {
        entryPoint: "src/menu.ts",
        imports: [
          { path: tuiOutput, kind: "dynamic-import" },
          { path: "@narumitw/pi-tui-kit", kind: "dynamic-import", external: true },
        ],
        inputs: { "src/menu.ts": {} },
      },
      [tuiOutput]: {
        entryPoint: "src/tui-menu.ts",
        imports: [{ path: "@narumitw/pi-tui-kit", kind: "dynamic-import", external: true }],
        inputs: { "src/tui-menu.ts": {} },
      },
    },
  };
}

test("eager graph validation preserves ticker menu boundaries and external packages", async () => {
  const builder = await loadBuilder();
  assert.doesNotThrow(() => builder.validateEagerGraph(validMetadata()));

  for (const forbidden of forbiddenEagerInputs) {
    const metadata = validMetadata();
    const entry = requireOutput(metadata, "dist/index.ts");
    entry.inputs = { ...(entry.inputs ?? {}), [forbidden]: {} };
    assert.throws(
      () => builder.validateEagerGraph(metadata),
      new RegExp(`First-use implementation is eager: ${forbidden.replaceAll("/", "\\/")}`, "u"),
    );
  }

  const eagerDependency = validMetadata();
  const entry = requireOutput(eagerDependency, "dist/index.ts");
  entry.imports = [
    ...(entry.imports ?? []),
    { path: "@narumitw/pi-tui-kit", kind: "import-statement", external: true },
  ];
  assert.throws(() => builder.validateEagerGraph(eagerDependency), /Eager external dependency: @narumitw\/pi-tui-kit/u);

  const bundledDependency = validMetadata();
  requireOutput(bundledDependency, "dist/index.ts").inputs = {
    "node_modules/example/index.js": {},
  };
  assert.throws(() => builder.validateEagerGraph(bundledDependency), /Bundled package input: .*node_modules\/example/u);
});

test("runtime build rejects destructive output paths and symlink escapes", async () => {
  const builder = await loadBuilder();
  const outside = await mkdtemp(join(tmpdir(), "pi-ticker-build-outside-"));
  const linkedParent = join(packageRoot, `.pi-ticker-build-test-link-${crypto.randomUUID()}`);
  try {
    await assert.rejects(
      builder.buildRuntime({ outputDirectory: packageRoot }),
      /Runtime output directory must be inside the package root/u,
    );
    await assert.rejects(
      builder.buildRuntime({ outputDirectory: join(outside, "dist") }),
      /Runtime output directory must be inside the package root/u,
    );
    await symlink(outside, linkedParent, "dir");
    await assert.rejects(
      builder.buildRuntime({ outputDirectory: join(linkedParent, "dist") }),
      /Runtime output parent must not escape the package root through a symlink/u,
    );
  } finally {
    await rm(linkedParent, { force: true, recursive: true });
    await rm(outside, { force: true, recursive: true });
  }
});

test("runtime builds are deterministic, mapped, external, and remove stale output", async () => {
  const builder = await loadBuilder();
  const root = await mkdtemp(join(packageRoot, ".pi-ticker-build-test-"));
  try {
    const first = join(root, "first");
    const second = join(root, "second");
    const firstMetadata = await builder.buildRuntime({ outputDirectory: first });
    await mkdir(join(second, "chunks"), { recursive: true });
    await writeFile(join(second, "chunks", "stale.js"), "stale", "utf8");
    await builder.buildRuntime({ outputDirectory: second });

    assert.deepEqual(await snapshotDirectory(first), await snapshotDirectory(second));
    assert.equal((await listFiles(second)).includes("chunks/stale.js"), false);
    const files = await listFiles(first);
    assert.ok(files.includes("index.ts"));
    assert.ok(files.includes("index.ts.map"));
    assert.ok(files.some((path) => path.startsWith("chunks/") && path.endsWith(".js")));
    for (const runtimePath of files.filter((path) => path.endsWith(".ts") || path.endsWith(".js"))) {
      const source = await readFile(join(first, runtimePath), "utf8");
      assert.match(source, /^\/\/ @generated by scripts\/build-runtime\.mjs/u);
      assert.doesNotMatch(source, /["']\.\.?\/[^"']+\.ts["']/u);
      assert.doesNotMatch(source, /["']\.\.?\/[^"']*src\//u);
      assert.ok(files.includes(`${runtimePath}.map`), `missing map for ${runtimePath}`);
    }
    for (const output of Object.values(firstMetadata.outputs ?? {})) {
      for (const input of Object.keys(output.inputs ?? {})) {
        assert.equal(input.includes("node_modules/"), false, `bundled package input: ${input}`);
      }
    }
    const { eagerInputs } = builder.validateEagerGraph(firstMetadata);
    for (const forbidden of forbiddenEagerInputs) {
      assert.equal(
        [...eagerInputs].some((input) => input.endsWith(`/${forbidden}`)),
        false,
        `${forbidden} became eager`,
      );
    }
  } finally {
    await rm(root, { force: true, recursive: true });
  }
});

test("generated import validation rejects missing targets and unsupported extensions", async () => {
  const builder = await loadBuilder();
  const root = await mkdtemp(join(packageRoot, ".pi-ticker-build-test-"));
  try {
    await mkdir(join(root, "chunks"), { recursive: true });
    await writeFile(join(root, "chunks", "present.js"), generatedBanner, "utf8");
    await writeFile(join(root, "chunks", "present.js.map"), "{}", "utf8");
    await writeFile(join(root, "index.ts"), `${generatedBanner}\nimport "./chunks/missing.js";\n`, "utf8");
    await assert.rejects(
      builder.validateGeneratedFiles(root),
      /Generated runtime import is missing: index\.ts -> \.\/chunks\/missing\.js/u,
    );

    await writeFile(join(root, "chunks", "missing.js"), generatedBanner, "utf8");
    await writeFile(join(root, "chunks", "missing.js.map"), "{}", "utf8");
    await writeFile(join(root, "index.ts"), `${generatedBanner}\nimport "./chunks/missing.mjs";\n`, "utf8");
    await assert.rejects(
      builder.validateGeneratedFiles(root),
      /Generated runtime import has an unsupported extension/u,
    );
  } finally {
    await rm(root, { force: true, recursive: true });
  }
});

test("generated runtime loads with Pi Jiti and exercises lifecycle and a lazy menu", async () => {
  const builder = await loadBuilder();
  const root = await mkdtemp(join(packageRoot, ".pi-ticker-build-test-"));
  const agentDir = join(root, "agent");
  const output = join(root, "dist");
  const previousAgentDir = process.env.PI_CODING_AGENT_DIR;
  try {
    await builder.buildRuntime({ outputDirectory: output });
    await mkdir(agentDir, { recursive: true });
    process.env.PI_CODING_AGENT_DIR = agentDir;
    const loader = new DefaultResourceLoader({
      cwd: root,
      agentDir,
      settingsManager: SettingsManager.inMemory({}),
      additionalExtensionPaths: [join(output, "index.ts")],
    });
    await loader.reload();
    const loaded = loader.getExtensions();
    assert.deepEqual(loaded.errors, []);
    assert.equal(loaded.extensions.length, 1);
    const extension = loaded.extensions[0];
    assert.ok(extension?.commands.has("ticker"));
    assert.ok(extension?.handlers.has("session_start"));
    assert.ok(extension?.handlers.has("session_shutdown"));

    const rpc = createRpcHarness([{ kind: "select", response: "Close" }]);
    const widgets: Array<{ key: string; content: unknown }> = [];
    const sessionManager = {};
    const ctx = {
      mode: "rpc",
      hasUI: true,
      sessionManager,
      ui: {
        ...rpc.ui,
        notify() {},
        setWidget(key: string, content: unknown) {
          widgets.push({ key, content });
        },
      },
    } as unknown as ExtensionContext;
    await emit(extension.handlers, "session_start", ctx);
    assert.deepEqual(widgets.at(-1), { key: "ticker", content: undefined });

    const command = extension.commands.get("ticker");
    assert.ok(command);
    await command.handler("", ctx as never);
    rpc.assertConsumed();

    await emit(extension.handlers, "session_shutdown", ctx);
    assert.deepEqual(widgets.at(-1), { key: "ticker", content: undefined });
  } finally {
    if (previousAgentDir === undefined) delete process.env.PI_CODING_AGENT_DIR;
    else process.env.PI_CODING_AGENT_DIR = previousAgentDir;
    await rm(root, { force: true, recursive: true });
  }
});

test("failed validation and publication preserve the previous runtime", async () => {
  const builder = await loadBuilder();
  const root = await mkdtemp(join(packageRoot, ".pi-ticker-build-test-"));
  try {
    const output = join(root, "dist");
    await mkdir(output, { recursive: true });
    await writeFile(join(output, "previous.ts"), "previous", "utf8");
    await assert.rejects(
      builder.buildRuntime({
        outputDirectory: output,
        validateOutput: async () => {
          throw new Error("injected validation failure");
        },
      }),
      /injected validation failure/u,
    );
    assert.deepEqual(await listFiles(output), ["previous.ts"]);

    const staging = join(root, "staging");
    await mkdir(staging, { recursive: true });
    await writeFile(join(staging, "next.ts"), "next", "utf8");
    let renameCalls = 0;
    await assert.rejects(
      builder.publishRuntime(staging, output, {
        renamePath: async (source, destination) => {
          renameCalls += 1;
          if (renameCalls === 2) throw new Error("injected publication failure");
          await rename(source, destination);
        },
      }),
      /injected publication failure/u,
    );
    assert.deepEqual(await listFiles(output), ["previous.ts"]);
    assert.deepEqual(
      (await readdir(root)).filter((entry) => entry.includes(".backup-")),
      [],
    );
  } finally {
    await rm(root, { force: true, recursive: true });
  }
});

async function emit(
  handlers: Map<string, Array<(...args: unknown[]) => Promise<unknown>>>,
  event: string,
  ctx: ExtensionContext,
): Promise<void> {
  for (const handler of handlers.get(event) ?? []) await handler({}, ctx);
}

function requireOutput(metadata: BuildMetadata, path: string) {
  const output = metadata.outputs?.[path];
  assert.ok(output, `missing fixture output: ${path}`);
  return output;
}

async function snapshotDirectory(directory: string): Promise<Record<string, string>> {
  const snapshot: Record<string, string> = {};
  for (const path of await listFiles(directory)) {
    snapshot[path] = await readFile(join(directory, path), "base64");
  }
  return snapshot;
}

async function listFiles(directory: string, prefix = ""): Promise<string[]> {
  const files: string[] = [];
  for (const entry of await readdir(join(directory, prefix), { withFileTypes: true })) {
    const relativePath = join(prefix, entry.name);
    if (entry.isDirectory()) files.push(...(await listFiles(directory, relativePath)));
    else if (entry.isFile()) files.push(relativePath.replaceAll("\\", "/"));
  }
  return files.sort();
}
